spring:
  application:
    name: peanut-web-phone-feign
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/static/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///peanutmi
    username: root
    password: root
  cloud:
    loadbalancer:
      retry:
        enabled: true
  redis:
    host: 106.13.73.229
    port: 6379
    password:
  mvc:
    static-path-pattern: /**
  data:
    mongodb:
      #uri: mongodb://testrw:testrw@localhost:27017/test
      uri: mongodb://106.13.73.229:27017/peanut
  banner:
    charset: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

server:
  port: 8084
  tomcat:
    uri-encoding: UTF-8

mybatis:
  configuration:
    auto-mapping-behavior: full
    aggressive-lazy-loading: true   #懒加载
    cache-enabled: true    #二级缓存
  type-aliases-package: com.peanut.entity

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

feign:
  hystrix:
    enabled: true

logging:
  level:
    com:
      peanut:
        dao: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  pageSizeZero: true
