spring:
  application:
    name: peanut-zuul
  #redis:
  #  host: 106.13.73.229
  #  port: 6379
  #  password:
  #session:
  #  store-type: redis

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

zuul:
  #ignoredServices: '*'
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 3000
  routes:
    phone:
      path: /api/a/**
      serviceId: peanut-web-phone-feign
    computer:
      path: /api/b/**
      serviceId: peanut-web-computer-feign
    api-c:
      path: /**
      serviceId: page-service